---
title: |
  How does visual information influence attitudes and behaviors about groups of people?
code-repo: |
  For replication, go to: <https://github.com/DamonCharlesRoberts/book_project/chapter_4>.
author:
  - name: Damon C. Roberts
    email: damon.roberts-1@colorado.edu
    orcid: 0000-0002-4360-3675
    title: PhD Candidate
    affiliations:
      - id: CU
        name: University of Colorado Boulder
        department: Political Science
        address: 333 UCB
        city: Boulder
        region: CO 
        postal-code: 80309-0333
abstract: |
  Previous chapters of this project demonstrate that the colors red and blue convey information about the partisan affiliation of another individual, and that this information influences a number of attitudes and behaviors. This chapter's goal is to add to these findings in a couple of directions: (1) do these findings generalize to shaping the attitudes and behaviors directed towards groups of people and (2) do these results contribute to the growing literature about the effects of polarization on seemingly non-political attitudes and behaviors?

bibliography: ["../../../assets/neighborhood-chapter-references.bib"]
format:
  hikmah-pdf:
    # Spit out in drafts directory
    latex-output-dir: "../../out/prr"
    # Use biblatex-chicago
    biblatex-chicago: true
    biblio-style: authordate
    biblatexoptions: 
      - backend=biber
      - autolang=hyphen
      - isbn=false
      - uniquename=false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    linestretch: 2
    fontsize: 12pt
date: today
nocite: |
  @allaire_quarto_2022
execute:
  echo: false
  warning: false
  message: false
  cache: false
params:
  replicate: false
---
{{< pagebreak >}}

# Introduction

The previous chapters demonstrated that the colors red and blue conveyed information about the partisanship of politicians and about potential discussion partners. The previous chapters also demonstrated that these effects on attitudes also influenced behaviors such as a willingness to vote for the candidate as well as willingness to have a conversation with another about politics. The previous chapter also demonstrated two other pieces to the story: (1) that the group-based information conveyed by the colors red and blue are dependent on the context, and (2) that the snap-judgments people form based on this simple visual information can shape attitudes and behaviors even when provided with more clear and explicit information about the partisan affiliation of another person.

In this chapter, I try to accomplish a few goals. First, I want to expand on the previous chapters by examining whether snap-judgments are used to evaluate groups of people. Second, I want to expand on the previous chapters by examining whether the previous findings extend to non-political objects. That is, this chapter seeks to further push my testing of the boundary conditions of the snap-judgment model. The third goal is that this chapter might address an important, but still yet to be solved, puzzle with the literature of partisan sorting that I discuss with more detail in the next section. 

To achieve these three goals, the chapter builds upon a growing set of work suggesting that the politicultural differences between Democrats and Republicans are shaping seemingly non-political attitudes and behaviors such as one's choice in which neighborhood to live in. I argue in this chapter that the prevalence of red and blue cars in the driveways of houses in a neighborhood shift people's perceptions of the partisan composition of the neighborhood, and as a result, will make people less willing to move to that neighborhood when they perceive they'd be in the political minority of that neighborhood. While these snap-judgments influence attitude expression toward reported willingness to move to a neighborhood, subsequent information such as job opportunities, performance of schools, average wages to cost of living ratio, and other information limits the efficacy of these initial judgments. This seems to provide one mechanism explaining why partisan sorting is not observationally as extreme as we might expect given extensions of the literature on affective polarization and experimental and self-reported survey evidence.

The implications of such findings corroborate existing work that suggests that there are an increasing number of cultural signals that people use to guess the partisanship of not just other individuals but groups of people, and that as a result partisanship and polarization are bleeding into our non-political decision-making. The implications of the argument advanced in the chapter build upon these existing findings by providing one causal mechanism as to the connection between cultural cues conveyed visually and the cognitive processing of such information. The chapter not only generalizes findings from the previous chapters to groups of people and to non-political attitudes and behaviors, but it contributes to a literature suggesting that political polarization is pervasive and is approaching universal.

# Politicultural differences and their effects

While political polarization certainly reflects a growing gap and consolidation of two camps of policy preferences and attitudes [@dellaposta_pluralistic_2020;@luders_attitude_2023], it manifests as something more consequential for our every-day experiences. Political polarization has come to reflect social groups that distinguish "us" versus "them" with increasingly fewer and fewer non-political social groups that are not wrapped up in our partisan group [@mason_uncivil_2018]. That is, we are not only holding fewer and fewer cross-cutting attitudes that moderate our political viewpoints [@luders_attitude_2023], but we also have fewer and fewer cross-cutting social groups that encourage interaction and experiences with perspectives of out-partisans [@mason_uncivil_2018]. The consequence of such phenomena is that we are becoming increasingly willing to harbor strong negative feelings towards those of the other political party and strong positive affectations to members of our political party [@iyengar_affect_2012;@iyengar_fear_2015].

The consequences of this affective polarization encourages discomfort being around those who identify with the other political party and finding comfort around those that share the same partisanship. In fact, some evidence suggests that it is even more sinister than comfort but rather predicts lower empathy for outpartisans [@allamong_screw_2021], as well as an increased willingness to describe outpartisans as subhuman [@martherus_party_2021]. Racists commonly use dehumanizing language to describe racial minorities [@utych_how_2018].

Evidence of this discomfort and its manifestations with out-partisans is piling up. For example, @carlson_what_2022 demonstrates that individuals perceive that they may incur social costs with friends and neighbors by engaging in a conversation with those they disagree with and expressing that disagreement, and avoid such situations as a result. Other work corroborate this finding by suggesting that individuals will be less likely to share the social media posts of political viewpoints they agree with if they perceive that they are in the political minority of those that would see that sharing of the post [@van_der_does_strategic_2022]. As a result of this tendency to speak out as a political minority in front of a group of people, individuals have fewer outpartisans in their group of folks they regularly discuss politics with [@butters_polarized_2022].

Building on this set of evidence, a growing area of the literature suggests that we are able to make inferences about the partisanship about other individuals, but we are able to do this for groups of people through the increasing politicultural distinctions between Republicans and Democrats. @hetherington_prius_2018 demonstrates that Republicans and Democrats are not just different in their policy preferences but rather that they live in different places and have different lifestyles. Others have replicated and built upon this work by suggesting that while there are many different types of lifestyles that Republicans and Democrats can take on, there is increasingly clear distinction between Republicans and Democrat archetypes [@rogers_politicultural_2022]. These politicultural distinctions are clear enough that we train a computer to make accurate guesses (upwards of 80%) of the partisanship by using only images of the cars in a particular neighborhood [@gebru_using_2017].

Though not inherently or necessarily political, our communities often collectively act in political ways. For example, some evidence suggests despite variation between counties' partisan composition and lockdowns discouraging people from leaving their homes during the COVID-19 pandemic, those living in Republican counties spent more time away from home than those living in Democratic counties [@roberts_polarized_2021]. Further, we see a place-based identity for rural individuals that predict partisanship [@cramer_politics_2016; see also @lyons_youre_2021] and characteristics like expression of anti-intellectual attitudes [@lunz_trujillo_rural_2022]. While place-based identities could be separate or informative of partisan identities, some literature argues that partisanship may actually inform which community we choose to make ours.

The consequences of the fewer cross-cutting social groups and increasingly homogenous cultural preferences of Republicans and Democrats manifest as dramatic differences in preferences about the communities that we are part of. @gimpel_seeking_2015 demonstrates that describing a neighborhood with explicit and implicit information (e.g., racial composition) about the partisan composition influences whether one expresses a desire or not to move and live there. Further work corroborates this finding by providing evidence from a number of studies which demonstrate that not only do people associate particular characteristics of a neighborhood such as the prevalence of churches with Republicans and hybrid cars with Democrats, but also that these features attract copartisans and repulse outpartisans [@motyl_how_2020].

Some work suggests, however, that these expressed preferences to live near copartisans do not carryover to migration patterns [see @iyengar_affect_2012]. In fact, there is some evidence suggesting that controlling for everything else but current rates of political sorting, we would have less political homogeneity than we had in 2008 [@martin_does_2020]. Further, evidence by @martin_does_2020 suggests that people switch their party registration after moving as opposed to moving to be more aligned with their party registration.

The literature on partisan sorting seems to conclude that people express a desire to sort into neighborhoods with partisans, but these attitudes do not turn into observable behaviors. The remainder of the chapter provides one explanation for this puzzle by demonstrating how the snap-judgment model may be at play. Much like the literature on the attitude expression of partisan sorting, the snap-judgment model heavily relies on the ways in which seemingly non-political information comes to be associated with one partisan group or another. The model also demonstrates how these snap-judgments are capable of having initial impacts on attitude expression, but its effects weaken in light of explicit and countervailing information.

# Snap-judgments explaining the puzzle of political sorting

As discussed thus far in the chapter, non-political objects are often associated with particular partisan leanings. For example, the modal car in a neighborhood conveys the partisan composition of the whole neighborhood [@hetherington_prius_2018;@gebru_using_2017]. In the same spirit as the rest of this book, we do not need to necessarily distinguish between whether someone drives a hybrid sedan and a Ford pickup truck. Information giving insight into one's partisanship may even be as subtle as their color choice in car. For a reader who thinks "hypothesizing about car color choice and partisanship is a reach", I agree. As stated at the outset of the chapter, the goal of the chapter is to extend past applications of the snap-judgment model to explicitly partisan objects such as yard signs as we did in Chapter 2 and to really challenge the model by looking at non-political objects that many never associate with partisanship.

Recall the snap-judgment model as depicted in @fig-theory. Extending the literature on partisanship as a superordinate social identity and affective polarization, we should expect that the partisan composition of a neighborhood would matter to people. In examining yard signs, @makse_politics_2019 demonstrate that people dislike having neighbors that do not share the same partisan affiliation as them. The motivation this comes from a desire to be in the majority of those around you with the same political views [see @van_der_does_strategic_2022]. While this appears to be something important to people, information about the partisan composition of a neighborhood might be inaccessible to most. Therefore, we are motivated to rely on heuristics to help with this [@motyl_how_2020]. One useful and efficient heuristic to convey partisanship is the use of color as other chapters have demonstrated. If we are concerned about the partisanship of our neighbors, we may rely on information such as the color of our potential neighbors' cars to infer their partisanship.

To most of us, we likely do not trust this as a basis to infer partisanship as other forms of information such as whether a potential neighbor is displaying a political yard sign. However, these usually only show up every couple of years during the election season and are displayed by those who tend to be highly politically active -- so, they are not universally displayed [@makse_politics_2019]. Absent explicit information about the partisan composition, we might be willing to accept that the information we are basing our inferences on as


{{< include ../../../assets/_theory.qmd >}}

# Experiments

- Make real estate flyers that are like a conjoint providing information about the neighborhood. Do something with a "favorite car in the neighborhood" and vary whether it is a red or a blue car.

{{< pagebreak >}}