---
subtitle: Professional development plan
format:
  fancy-doc-pdf:
    toc: false
    latex-output-dir: ../out/
    biblatex: true
    filters:
      #- "_extensions/andrewheiss/wordcount/citeproc.lua"
      - "_extensions/andrewheiss/wordcount/wordcount.lua"
author:
  - name: Damon C. Roberts
    affiliations:
      - name: Univeristy of Colorado Boulder
    email: damon.roberts-1@colorado.edu
bibliography: ../../../assets/references.bib
---

After completing my dissertation, I plan to continue researching visual information in politics as a Post-Doctoral researcher and an Assistant Professor. So far, I have presented parts of this dissertation project at the International Society of Political Psychology's annual conference, and at the Front Range American Political Science Association's annual conference. I intend to present this research in other workshops and outlets in the coming year.

I also have long-term goals for this project to be the start of a career-long effort to study this topic. I plan to publish this dissertation as a book project. While the project, in its current form, focuses on  the colors red and blue, the goal is to turn this into a broader treatment of visual information in politics. To do this, I want to examine other types of related visual information, such as other colors that are less tied to the current political parties (e.g., the use of the colors black and white). That is, I plan to examine the use of these (and other) colors in Black Lives Matter and Blue Lives  Matter organizations, and to further examine symbols in politics/how symbols interact with color. I have discussed alternative projects with Gijs Schumacher at the Hot Politics Lab located at the University of Amsterdam.

In this dissertation I aim to outline a psychological and cognitive framework for exploring simple forms of politically-relevant information. Ideally, I hope to organize/collaborate with a lab of scholars interested in studying the role of visual information in politics. Further, I intend to share this work with several consultants working at political marketing firms who have shared their experiences with me about how candidates make decisions about things like yard signs.

<!--
After my degree, I plan to continue researching visual information in politics as a Post-Doctoral researcher and an Assistant Professor at another institution. So far, I have presented parts of this dissertation project at the International Society of Political Psychology's annual conference and the Front Range American Political Science Association's annual conference. I intend to present this research in other workshops and outlets in the coming year.

I also have long-term goals for this project to be the start of a career-long effort to study this topic. I plan to publish this project as a book project. While the project, in its current form, focuses on the colors red and blue, the goal is to turn this into a broader research agenda. To do this, I want to examine other types of related visual information, such as other colors that are less tied to the current political parties, such as the use of the colors black and white, to examine their use in Black Lives Matter and Blue Lives Matter organizations, to examine symbols in politics and how they interact with color and have discussed alternative projects with Gijs Schumacher at the Hot Politics Lab located at the University of Amsterdam. This dissertation aims to provide an early attempt to outline a psychological and cognitive framework to explore simple forms of politically-relevant political information. Ideally, I can organize a lab of scholars interested in studying the role of visual information in politics. Further, I intend to share this work with several consultants working at political marketing firms who have helped me in the project so far by sharing their experiences about how candidates make decisions with colors on their yard signs.
-->