# A theory of processing politically-relevant visual information

In this chapter I will present a theory of how political visual objects are used by the public to make decisions. As I will argue throughout the chapter, existing models of political information processing set the foundation for the theory I present here. However, there requires adjustment to the underlying cognitive mechanisms to account for differences in how the brain processes visual information relative to things like a stated policy position of a political candidate that you read in the news paper or hear while watching a video.

While I intend for the theory to be one in which scholars can apply to a number of different types of visual information, the rest of this project will focus on an almost universal and commonly covered form of visual information used in politics: color. I do this for a few reasons. First, color is so salient in politics that we often describe partisanship by associated colors. For example, Iowa is a "red state" whereas New York is a "blue state." Professional political scientists also tend to use the colors red and blue in the titles of their peer-reviewed papers to indicate the paper's topic being on partisanship. One example would be @goggin_what_2020 with the title of a paper being, "What Goes with Red and Blue? Mapping Partisan and Ideological Associations in the Minds of Voters". Second, color is one of the most simple forms of visual information that we receive. Given this, color seems to not only be an important starting place but it also allows for the focus to be on the foundations of how visual information is processed as opposed to immediately adding too many layers of complexity that I risk undertheorizing about the key mechanisms and overtheorize about nuances that do not apply in most real-world cases.

Why is it necessary for me to start with simple cases? Visual information, at large, is comparatively understudied in the field. The field largely considers information that are quite common and explicitly political such as stated policy preferences, conversations with our friends about politics, and text with political information from the news or campaigns. This is not an indictment on the field. In fact, political psychologists have made significant strides to theorize about political information processing. The dominant theories coming from these interdisciplinary efforts are at the core of the theory that I present here. The reason there is relatively little theorizing about visual information and not more explicitly political information is likely due to the methodological challenges that come with theorizing about visual experiences.

Relative to these more traditionally considered forms of information, visual information is much harder to pin down. Though, for many of us, visual information is ubiquitous, it is highly contextual information. As I will elaborate upon more later in this chapter and in [Chapter 3](../../chapter_3/manuscript.qmd), colors like red and blue can represent different things in different contexts and, as a result, have different effects on other forms of cognitive processing. Not only is visual information quite complex, but theorizing about it becomes harder when we consider how interdisciplinary the theorizing becomes. To not operate in a vacuum, a scholar who wants to theorize about the role of visual information in politics should consider fields such as neuroscience, psychology, marketing, and communication. I agree with @bucy_editors_2021 who discuss this challenge to the study of visual politics when they argue that each of these fields have their own methodological and generative modelling traditions, but they also apply their theories to many different contexts that may not necessarily be easily mappable to political science. These features make it quite difficult for political scientists to take some of these theories and apply it to politics though it may seem to be important low-hanging fruit.

While it may be difficult, these efforts are worthwhile. As I will discuss, the key implication of the theory is that visual information will shape the pre-conscious processing of this more explicitly political information. In other words, the model suggests that the visual information that we consume will impact the degree to which we accept and the attitudes we express in response to explicitly political information; we form an impression or a snap-judgment that will influence the information that comes afterwards. This would help us further refine our understanding of how voters can make decisions with relatively little information, whether or not we will have a conversation with others about politics, and how we form impressions about the political leanings of groups of people to name a few examples.

Before presenting a theory of visual information processing in politics, I will first discuss the dominant models of political information processing. As I have mentioned, the mechanisms outlined in these theories are at the core of the theory that I present. Both practically and conceptually, my model of visual information processing amends these existing models so that they may better generate predictions about how visual information influences political cognition. After introducing some of the key mechanisms outlined in those theories, I will present the theory that is the focus of the book. I will refer to this theory as the snap-judgment model of political information processing. Once I explain this theory, I will close this chapter with a discussion about how this contrasts with existing theories of political information processing, but I will more importantly discuss how this theory contributes to these existing models.

## The two canonical models of political information processing

There are two dominant models of how the public in the United States process political information and express attitudes in response to such information. There are, of course, many more than these two; particularly in the fields of survey and public opinion research [see @tourangeau_psychology_2000]. I will focus on the two most commonly used in political science, however, as they synthesize many of these other alternative models and are quite commonly used by political psychologists.

Zaller's [-@zaller_nature_1992;@zaller_simple_1992] "memory" model of political information processing and attitude expression is one of the most popular psychological models in political science. As opposed to viewing citizens as Aristotle's ideal democratic citizens, this "memory" model characterizes citizens as flawed Bayesian updaters. While the application of this model largely focuses on the model's implications for how we express an attitude by "Sampling" from our existing knowledge, this model characterizes how we "Receive" and "Accept" new information. 

In the "memory" model, @zaller_nature_1992 characterizes the public as Bayesian updaters who, when gathering information about politics, will develop a cognitive schema about how that information relates to existing information. That is, citizens are not passively consuming political information from political elites -- which is much of the focus in @zaller_nature_1992. Rather, the public actively integrate this information. Nevertheless, they do not weigh all new information the same. The public have a number of "predispositions" that have influence on the degree to which and *how* we organize this new information. As a result of these features, not all new political information will prove influential in our expressed political attitudes all of the time.

To help readers view the key contributions of the memory model, I summarize the basics in @fig-zaller-model which emphasizes the key processes involved in processing new information, incorporating, and then using that information to express an attitude. Though the figure is extremely simplistic, each node reflects a step in the model. We see that at each step, various predispositions mediate the relationship between the Receive-Accept and Accept-Sample nodes.

```{mermaid}
%%| label: fig-zaller-model
%%| fig-cap: Memory model of political information processing
%%| fig-width: 5
%%{init: {'theme':'base', 'themeVariables':{'primaryColor':'#ffffff', 'primaryBorderColor': '#000000'}}}%%
flowchart TB
    direction TB
    A[New information from a political elite] -->|"Predispositions (e.g., Ideology and sociodemographics)" | B[Receiver adds the new information to their schema]
    B -->|"Predispositions (e.g., Ideology and sociodemographics)"| C[Receiver expresses an attitude based on the schema]
```

The next canonical model of political information processing is Lodge and Taber's [-@lodge_rationalizing_2013] "online" model. This model also views the public as selectively incorporating Bayesian updaters. Like Zaller's [-@zaller_nature_1992] "memory" model, the Lodge and Taber's [-@lodge_rationalizing_2013] "online" model is heavily interdisciplinary. However, they characterize this "Receive" and "Accept" processes of political information as slightly different with significant implications.

One of the psychological theories that Lodge and Taber incorporate into their model of psychological processing is referred to as "motivated reasoning" [see @taber_motivated_2006]. The psychological theory of motivated reasoning suggests that the degree to which we gather new information that goes against our pre-existing viewpoints depends on which motivation we presently have. In summarizing this theory, @kunda_case_1990 argues that in contexts where we are motivated to gather information so that we are accurate we are more likely to incorporate all new information; even new information that challenges our pre-existing views. However, according to @kunda_case_1990, we often default to the motivation of selectively gathering information that fits with our pre-existing views in an attempt to have more evidence that we can cite to defend our position to those who may wish to challenge them. This theory of motivated reasoning has been and is still quite popular among social psychologists who examine how members of social groups might justify their negative views of those in another group while maintaining positive views of those in their own group, despite the presence any contradictory evidence [see @redlawsk_affective_2010]. 

Though, Zaller's [-@zaller_nature_1992] considers the role of ideology as one of the "predispositions" that influence the reception and acceptance of new information, Lodge and Taber's key innovation is that partisan identity and the degree to which we are motivated to defend the political perspectives of our partisan confederates is **the** pre-disposition that influences the degree to which we consider new information [@lodge_rationalizing_2013]. This perspective predicts that rather than the public appearing to be somewhat regularly biased, but also inconsistent, in expressing their attitudes about something in the face of new information, this model suggests that the public are somewhat predictably going to gather information and express attitudes that align with those of those holding the same partisan identification. This model has been significant for informing theories around political polarization in the United States as well as conversations around the degree to which political persuasion is possible with the public.

Another feature of Lodge and Taber's [-@lodge_rationalizing_2013] model is that it considers the role of affect. Throughout this book, I conceptualize affect as valanced (positive or negative) reactions to some political object. This departs from conceptualizations popular among political scientists where some see it as somewhat synonymous with emotion [see @marcus_affective_2000]. However, I depart with this to align with popular conceptualizations that distinguish affect from emotion where affect is a pre-conscious valanced reaction to an object and I conceptualize emotion as a discrete or categorical classification of these valanced reactions which require some degree of conscious processing [see @sander_cambridge_2013]. In the online model, they include the theory of affect transfer which, when we conceptualize the brain as a network of interconnected nodes [see @collins_spreading-activation_1975], suggests that if an individual dislikes, for example, a directive to ICE that limits the number of deportations that they can carry out then we would predict that the same individual would also dislike a directive that extends protection to children of non-documented parents that immigrated to the United States by enrolling in the DACA program due to the person's preferences for restrictive immigration. This aligns with popular conceptualizations of how attitudes form by considering memories as heavily affectively-laden [@fazio_attitudes_2007].

Relative to Zaller's [-@zaller_nature_1992] memory model, the online model is much more permissive of context. Besides the rhetorical devices that the particular messenger uses and the pre-dispositions that the receiver has, Lodge and Taber's [-@lodge_rationalizing_2013] model presents a situation where there are many more mediating factors that influence these processes. The degree to which we are motivated to engage with this information in the first place depends on particular motivations that we may have such as to gather accurate information or information that makes us feel more confident that our pre-existing preferences are accurate. As a result of emotion, predispositions such as anxiety can induce this accuracy motivation [@marcus_affective_2000]. Further, we do not just consume this information but the degree to which this information evokes a directionally valanced evaluation depends on what prior information is salient (or "hot" in line with Lodge and Taber's [-@lodge_rationalizing_2013] use of the phrase from the theory of hot cognition) when we consume this new information.

While there are some differences between these models, they also agree on foundational perspectives of how memory is used to generate attitudes. The first is the perspective that information is organized in a schema. This conceptualization borrows significantly from the perspective that the brain is organized as a set of associated nodes in a network [@collins_spreading-activation_1975]. This perspective has been foundational for a number of fields that study cognition. In this perspective, the cognition works because we have nodes which identify a particular piece of information. These nodes are connected to each other in a mental schema; or some structured organization of information [@collins_spreading-activation_1975;@kahana_laws_2022]. These connections between nodes, however are not equally strong [@fazio_attitudes_2007]. Rather, the strength of these nodes depend on a variety of features [@fazio_attitudes_2007;@kahana_laws_2022]. Though the memory and online model vary in which features matter for influencing the strength of these nodes, they still consider the influence of activated confounding information that can make some of these connections between nodes more relevant than others. As a result, both models suggest that we do not just gather information and then just perform some arithmetic on a pros and cons list. Rather, the degree to which a new node is added and used in the future depends on which nodes it is attached to when being encoded as memory.

For the purposes of this project, a key commonality between these models is that they are theorizing about how pre-conscious cognitive processes not only shape how we interpret our political world but also how these processes shape how we react to this political reality. These models are widely cited and inform most contemporary political psychology. One way in which we can build upon the impact of these models is to consider forms of information that are perhaps more common than text or persuasive arguments provided political elites is by adjusting these models to account for visual information. Many of the fundamentals present in these models are necessary to theorize about visual information. Nevertheless, making slight adjustments to consider the temporal ordering of what types of information are processed first has significant implications for how we understand what influences our understanding of the political world and how the public come to express an attitude.

## Gathering the pieces to the puzzle

Existing models of information processing in politics are largely considered in the context of consuming news and following statements by politicians and political candidates. I argue that there is another way in which politicians may communicate information with the mass public that has significant downstream impacts on political cognition and attitude expression: visual information.

Let me first start off by departing from talking about politics for a minute and consider a related topic: marketing and the role of color. Visual branding is a significant factor in predicting consumer behavior. Marketing is not simply producing catchy slogans but is also about how to visually present a brand. There is ample evidence suggesting that choices in visual presentation has significant influence on whether or not a consumer will purchase one of your products. For example, evidence suggests that hotels that have colors like red are much less likely to be booked relative to hotel rooms that feature softer colors like blues and beiges [@kuo_impact_2023].

As this example demonstrates, color is a significant form of visual information that can influence how we behave. But, why? There is a rich literature in marketing referred to as color theory which suggests that colors evokes particular affective and emotive reactions. For example, @cimbalo_emotionally_1978 demonstrates that colors like red and blue contain different emotive associations. Specifically that red can evoke negative emotions and blue can contain positive and more soothing emotions.

Connecting this idea to that of the work that conceptualizes memory as an associative network, colors are not simply just something that exists but it is a node that contains its own associations. Like any node or memory, color does not have to hold one connection nor do all connections have equal strength under every circumstance. Let me illustrate this with a simple example.

```{mermaid}
%%| label: fig-color-associations
%%| fig-cap: Colors are associative nodes
%%| fig-width: 5
%%{init: {'theme':'base', 'themeVariables':{'primaryColor':'#ffffff', 'primaryBorderColor': '#000000'}}}%%
flowchart LR;

A[Yellow] --> B[Sweatshirt]
A --> C[Banana]
A --> D[Sunrise]
A --> E[Los Angeles Rams]
```

@fig-color-associations presents all the different things that we may associate the color yellow with. We might associate it with our favorite sweatshirt; with a food item, a banana; the sunrise; and the Los Angeles Rams. You may think of different things when you think of the color yellow. This is because you may have different connections to the "yellow node" in your head than I do. This arises with different experiences and differences in the salience of those associations because of your cognitive schema. However, 3 months from now you may think of different things when asked what you associate with the color yellow. This is because your schema is reorganized or different aspects of your schema are accessed because of the context you are in. Perhaps, today you think of the Los Angeles Rams, but say 3 months from now it is April and you are thinking about the Milwaukee Brewers because it is now baseball season and the Super Bowl happened a couple months ago.

Complicating this a bit more, we do not only hold these associations with particular objects, but theories of associative memory suggests that nodes in our pre-existing cognitive schemas are highly multi-dimensional [@kahana_laws_2022]. We can see the most simple example of this in @fig-color-associations. We can think of the color yellow as being associated with clothing items, food items, a time of day, and a sports team. Associations with the color yellow are not only constrained by the type of object it is such as only food items. A more complicated example is that the color yellow can also contain differing affective associations too depending on the object.

Colors can contain affective associations through connections to the affective associations we have with related objects. Affect is a strong and central part to human memory [see @fazio_attitudes_2007;@kensinger_affective_2022]. When we think back to some event in our life, rarely do we only recall what happened but we often recall how it made us feel -- and sometimes we may start to feel happy, angry, or fearful like we did in that recalled event. This is because memories are simply refired electrical signals between a particular network of neurons that were originally active during experiencing (encoding) the event [@fazio_attitudes_2007]. Going back to the idea of affect transfer, as discussed by Lodge and Taber [-@lodge_rationalizing_2013] who applied in in the context of politics, colors contain affective information not necessarily as a result of any inherent property about the color but because of the affect that comes with the objects that we commonly associate with that color [@cimbalo_emotionally_1978].

So, what does this mean for politics? As the first chapter discussed, colors have been present throughout the political history of the United States. Politicians and political candidates are conveying information to potential voters and to the public when they select particular colors. This occurs through the same cognitive mechanisms that I have discussed thus far. As we gain more experience with connecting particular colors to a particular political idea or set of political ideas, the strength connecting these nodes increases and makes it a more central part of our cognitive schema. Over time, we build these associations with visual information and particular political ideas or political individuals. The associated affective responses that we have to those political ideas or figures can transfer onto those colors as we strengthen the association of the color with the political ideas or figures.

In the context of the United States, the colors red and blue are ubiquitous in politics. Since the 2000 Presidential Election, news organizations have consistently converged on the use of the colors red and blue to convey to the public whether the Republican or the Democrat, respectively, won a particular electoral district [@elving_color_2014]. Extending these ideas about how associations between color and some object can come to form in the brain, we may expect that the associations of the colors red and blue with Republicans and Democrats in the United States would occur.

It is not only that associations between a particular political party and their ideas or prominent figures are associated with these colors, but we may expect that it will have significant political consequence. Going back to the role of colors in marketing and consumer behavior, a foundational idea for this theory is that the affective associations with a color has downstream effects on behavior. In non-political contexts, there is a rich literature in affective neuroscience and cognition that traces the evoked affect to behavioral outcomes in a wide-variety of contexts [@kensinger_affective_2022]. In fact, these ideas have been debated in cognition all the way back to the father of modern Biology and Evolutionary Psychology, Charles Darwin, and has been an area of scientific debate ever since. In political science, there is a rich area of political psychology focused on tracing emotive and affective reactions to political information to behavior. For example, @marcus_affective_2000 develop Affective Intelligence Theory which argues that anxiety induces information-seeking behavior among the public and can be a strong predictor of following politics more closely. @lodge_rationalizing_2013 builds on this Affective Intelligence Theory and argues how this can influence motivated reasoning. Adding more nuance to these arguments, @pheonix_anger_2019 also has discussed the implications of stereotypes for Black Americans and how Black Americans can engage in emotional restraint to not express Anger which is an emotion induced from moral outrage that can have a positive effect on political participation. In short, emotion and affect are common in politics and that it has significant predictive power for political behavior.

So, where do these ideas leave us? Building upon all of these ideas, we have all of the pieces to build the puzzle that is understanding how visual information is involved in politics. This is the objective of the next section.

## A theory of how visual information matters to politics

Visual information is processed extremely quickly. For example, @ames_impression_2012 demonstrate that to form an impression about another based on visual information of a social interaction takes only about 33 milliseconds (abbreviated as ms). Going back to our days in high school physics, we may recall that light travels faster than sound as it requiring some degree of matter for it to travel by. This is why in the vacuum of space, light travels much easier relative to sound. Not that sound does not travel in space, it is just much slower.

If we are receiving this visual information first, then we might expect that the pre-conscious cognitive mechanisms start the process of political cognition before traditionally considered mediums of political information. So, let's more directly discuss this cognitive process in politics now that we understand the relevant fundamentals of cognition.

First, we receive visual information as wavelengths that are passed to our retina. Our retina passes this information to our optic nerve as an electrical signal to our visual cortex. Once in our visual cortex, the process of connecting those nodes of visual information in the cortex activates the paths to related nodes across our brain [@goldstein_sensation_2017]. While this glosses over important physiological components such as the role of ganglion cells and the differences between the V1 and V4 sections of the visual cortex, this still illustrates how the information is received and starts those now familiar cognitive processes.

Once the visual information has been decoded, our brain will want to find information, or meaning, from those electrical signals. It therefore starts looking down all of these forking paths that connect nodes together. In other words, the associative network has been activated. Once activated, we will continue to spend effort on paths that continually provides more relevant information and will abandon paths that are less relevant and informative.

As affective neuroscientists argue, we are not only accessing memories associating the color yellow with a sweatshirt, but we are also looking for associated nodes that contain affective information as well [see @kensinger_affective_2022]. Such as yellow with a clothing item that we like. Once we make these connections, we will have an affective response to this newly decoded visual information as informed by related visual information that contains affective information.

So, how does this work with political visual information? @fig-theory presents what I call the snap-judgment model of politically-relevant visual information processing.

{{< include ../../assets/_theory.qmd >}}

When in a political setting, one should be primed to expect that the information will contain political messages or is designed to convey political information. Similar to being in a department store and seeing yellow out of the corner of one's eye, an individual would be much more likely to expect to see a sweater as opposed to a banana. The reverse is true if one were in a grocery store instead of a department store. What this means for politics, critically, is that visual information that can be political and non-political will depend on whether or not one is in a context that receiving information about politics makes sense. For example, one would not be surprised to receive visual information about politics when watching advertisements during election season or at a political rally, but would be surprised and confused if this happened when attending an NBA game. Likewise, one would be surprised and perhaps confused to see information about the NBA at a political event rather than information about politics. This is a central boundary condition for this theory: not all visual information is political all of the time. This is because information as nodes can be associated to a number of different things and we can find different meanings from them in different contexts.

Once one consumes visual information about politics, this cognitive process that I have belabored is activated. One will seek to find political meaning from that visual information. This pre-conscious process that the brain starts will go down these finite forking paths to find which associated node provides information about the current stimulus. 

Since politics is primed, it is likely more successful and efficient to search through nodes related to politics and not any and everything that can conceivably be related. So, the brain elects to look through potentially relevant nodes that are part of a cognitive schema about politics. The brain continues to refine which paths it goes down by finding paths with strong associations -- or high amounts of similarity to the stimulus. 

Once identifying a node or set of connected nodes, affect transfer would enable me to form an impression or a reaction to that political information. This affect transfer enables a behavioral response: to continue to engage or disengage from an object.

As this is a pre-conscious process, the attitude that I rely upon to make a decision about whether to continue interacting with the source of this information will be a valanced affective response as opposed to a cognitive and more laborious process of having an emotive and more nuanced reaction. This valanced response will either encourage me to disengage from the object or to continue engaging with it [@sander_cambridge_2013].

In politics, negatively valanced information often encourages a disengagement motivation while positively valanced information encourages continued engagement [see @lodge_rationalizing_2013;@valentino_election_2011]. For example, those who are Democrats who come across a Donald J. Trump rally, they may be much more likely to be motivated to disengage and change the channel or scroll to the next video than a Republican who might have more positively valanced associations with Trump than a Democrat. Evidence for tendencies like this play out in a number of different settings in the affectively polarized era that characterizes contemporary politics in the United States [see @mutz_hearing_2006;@iyengar_affect_2012;@iyengar_origins_2019].

Once these motivations have been activated, we are likely to stay disengaged or engaged with the political object unless new information countervails that. That is, we have an encoded memory that suggests an object is negative or positive and to change these motivations will requires some degree of changing our mind. This new information could be more visual information, or it could be information that is processed later such as a stated policy position. The cognitive process of finding meaning in the new information restarts and is evaluated to either be negative or positively valanced. Once making that determination, our affective state (the total state of how we feel) will directionally remain the same, or it will adjust.

Critically, however, the information that we temporally process first will carry significant weight relative to the new information. As time goes on, memory falters and we do not remember all of the details of the information [@kahana_laws_2022]. Critically, what remains is the affective state the information encouraged but not necessarily all of the details [@kahana_laws_2022; see also @lodge_rationalizing_2013]. As that information is then encoded as memory and becomes part of your cognitive schema that will be used to form a "snap-judgment" of subsequent experiences.

Critically, what this model implies is that simple information that is temporally processed *before* more complicated forms of information will shape our actions and perceptions of any subsequent information. For simple visual information such as color, this means that color can be a significant influence on how we perceive and respond to substantive political information such as a stated policy position. Let me illustrate the implications of this with an example.

Previous models of political information processing would examine how a Democrat and a Republican may differentially respond to viewing a speech orated by Donald J. Trump. The memory-based model would suggest that highly informed Democrats and Republicans, who have a robust ideological schema would be less persuaded than those who are less informed. In that situation, highly informed Democrats would be much less likely to express agreement with Trump or to change their position. Meanwhile, highly informed Republicans may be less persuaded, but because they already agree with Trump's positions. Less informed Republicans and Democrats may be more open to persuasion due to the fact that this new information from Trump is not drowned out by the significant information that may countervail the new information provided by Trump. The online model diverges from this to argue that the fact that Trump is speaking, Democrats are already likely to be motivated to not even consider any of the information that Trump is providing while Republicans will be much more willing to accept all of it.

Before Trump even goes to speak at the podium, however, these Republican and Democratic viewers are met with a lot of visual information of the stage. Perhaps they see a stage with a red backdrop -- one that is descriptively associated with Republicans [see @elving_color_2014;@schloss_politics_2014]. In agreement with the online model that refines the memory-based model, I should expect that these colors have already activated a cognitive process which encourages the affective state and motivations to disengage or engage more with the television before Trump has even entered the stage.

The next chapter explores a common example of political marketing: yard signs. The goal of the chapter is to establish whether visual information in politics is considered by voters at all. It also allows for me to present evidence suggesting that voters consider the colors red and blue to be information about the partisanship of a political candidate in a situation where they lack more information about them (since it is a fictional candidate for a fictional election). The remaining chapters not only consider different contexts in which these colors can convey information about partisanship and the behavioral consequences, but they also consider claims I make in this chapter such as the highly contextual nature of this information as well as the downstream effects that the snap-judgment generated from visual information has on the effects of traditional political information subsequently processed on attitude expression.